### ISSUE TITLE
hi i have a doubt about the disparity input

### ISSUE THREAD

**Issue by lvZic** [yshen47/InfiniteNature-PyTorch#1]
I wanna use "google_earth.yaml" instead of default "infinite_nature_default.yaml". So  which the range of input disparity by MIDAS should be in ? [0, 1] or [?]

**Comment by yshen47** [comment]
"google_earth.yaml" is not supported for this project

**Comment by lvZic** [comment]
> "google_earth.yaml" is not supported for this project

so, the pretrained ckpt is just for "infinite_nature_default.yaml", right?

**Comment by yshen47** [comment]
yes
